app/Http/routes.php
<?php

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    // return what you want
});


Route::get('/kill-sessions', function() {
    $request->session()->flush();
});


Route::get('refresh-csrf', function(){
    return csrf_token();
});

// Route::auth();

// FRONT END

Route::any( '/', [
	'as'   => 'frontend.index',
	'uses' => '\App\Http\Controllers\Frontend\HomeController@index',
] );


Route::any( '/about', [
	'as'   => 'about',
	'uses' => '\App\Http\Controllers\Frontend\HomeController@about',
] );

Route::any( '/contact', [
	'as'   => 'contact',
	'uses' => '\App\Http\Controllers\Frontend\HomeController@contact',
] );


Route::any( '/privacy', [
	'as'   => 'privacy',
	'uses' => '\App\Http\Controllers\Frontend\HomeController@privacy',
] );

Route::any( '/terms', [
	'as'   => 'terms',
	'uses' => '\App\Http\Controllers\Frontend\HomeController@terms',
] );


Route::any('/search', [
        'as' => 'post.search', 
        'uses' => '\App\Http\Controllers\Frontend\PostController@search',
]);

Route::any('/api/post/search', [
        'as' => 'api.post.search', 
        'uses' => '\App\Http\Controllers\Frontend\PostController@apiSearch',
]);


Route::any('/property/{slug}', [
        'as' => 'post.detail', 
        'uses' => '\App\Http\Controllers\Frontend\PostController@detail',
]);


Route::get( '/register', [
	'as'   => 'register',
	'uses' => '\App\Http\Controllers\Frontend\UserController@getRegister',
] );


Route::post( '/register', [
    'as'   => 'register',
    'uses' => '\App\Http\Controllers\Frontend\UserController@postRegister',
] );

Route::any( '/login', [
    'as'   => 'login',
    'uses' => '\App\Http\Controllers\Frontend\AuthenticateController@login',
] );

Route::any( '/logout', [
    'as'   => 'logout',
    'uses' => '\App\Http\Controllers\Frontend\AuthenticateController@logout',
] );



// Route::any( '/resetpassword', [
// 	'as'   => 'resetpassword',
// 	'uses' => '\App\Http\Controllers\Frontend\UserController@resetpassword',
// ] );




Route::group(['middleware' => 'auth'], function () {

	Route::any('/create', [
        'as' => 'post.create', 
        'uses' => '\App\Http\Controllers\Frontend\PostController@create',
	]);


	Route::any('/property/{slug}/edit', [
	        'as' => 'post.edit', 
	        'uses' => '\App\Http\Controllers\Frontend\PostController@edit',
	]);
    Route::any('/property/{slug}/close', [
            'as' => 'post.close', 
            'uses' => '\App\Http\Controllers\Frontend\PostController@close',
    ]);

	Route::any('api/property/create', [
	        'as' => 'api.post.create', 
	        'uses' => '\App\Http\Controllers\Frontend\PostController@apiCreatePost',
	]);
	Route::any('api/property/update', [
	        'as' => 'api.post.update', 
	        'uses' => '\App\Http\Controllers\Frontend\PostController@apiUpdatePost',
	]);
	Route::any('/property/{id}/delete', [
	        'as' => 'post.delete', 
	        'uses' => '\App\Http\Controllers\Frontend\PostController@delete',
	]);

    Route::any('/api/wishlist/addwishlist', [
        'as' => 'api.wishlist.add_wishlist', 
        'uses' => '\App\Http\Controllers\Frontend\WishlistController@apiAdd',
    ]);

    Route::any('/api/wishlist/removewishlist', [
            'as' => 'api.wishlist.remove_wishlist', 
            'uses' => '\App\Http\Controllers\Frontend\WishlistController@apiRemove',
    ]);

});



// FRONT END
Route::group(['as' => 'frontend.auth.', 'namespace' => 'Frontend', 'middleware' => 'guest'], function () {
    // Route::get('/register/success', ['as' => 'register.success', 'uses' => 'AuthenticateController@getRegisterSuccess']);
    // Route::get('/register', ['as' => 'register', 'uses' => 'AuthenticateController@register']);
    // Route::post('/register', ['as' => 'register', 'uses' => 'AuthenticateController@postRegister']);
    Route::post('/ajax/login', ['as' => 'login', 'uses' => 'AuthenticateController@postLogin']);
    Route::post('/ajax/logout', ['as' => 'logout', 'uses' => 'AuthenticateController@postLogout']);
    Route::get('/auth/token/{email}/{token}',
      ['as' => 'emailConfirm', 'uses' => 'AuthenticateController@confirmEmail']);
    Route::get('/password/reset', ['as' => 'password.reset', 'uses' => 'AuthenticateController@getPasswordReset']);
    Route::post('/password/reset', ['as' => 'password.reset', 'uses' => 'AuthenticateController@postPasswordReset']);
    Route::get('/password/{email}/{token}/new',
      ['as' => 'password.new', 'uses' => 'AuthenticateController@getPasswordNew']);
    Route::post('/password/{email}/{token}/new',
      ['as' => 'password.new', 'uses' => 'AuthenticateController@postPasswordNew']);
    // social;
    Route::get('/auth/facebook',
      ['as' => 'facebook.callback', 'uses' => 'AuthenticateController@authFacebook']);
    Route::get('auth/facebook/callback', ['as' => 'facebook', 'uses' => 'AuthenticateController@authFacebookSocial']);

    Route::get('/auth/google',
      ['as' => 'google.callback', 'uses' => 'AuthenticateController@authGoogle']);
    Route::get('auth/google/callback', ['as' => 'google', 'uses' => 'AuthenticateController@authGoogleSocial']);
});

Route::group(['as' => 'frontend.profile.', 'namespace' => 'Frontend', 'middleware' => 'auth'], function () {
    Route::get('/edit', ['as' => 'edit', 'uses' => 'ProfileController@edit']);
    Route::post('/edit', ['as' => 'edit', 'uses' => 'ProfileController@postEdit']);
    Route::get('/change-password', ['as' => 'change-password', 'uses' => 'ProfileController@changePassword']);
    Route::post('/change-password', ['as' => 'change-password', 'uses' => 'ProfileController@postChangePassword']);
    Route::post('/me/upload-picture', ['as' => 'me.upload-picture', 'uses' => 'ProfileController@uploadPicture']);
    Route::get('/me', ['as' => 'me', 'uses' => 'ProfileController@me']);
    Route::get('/wishlist', ['as' => 'wishlist', 'uses' => 'ProfileController@wishlist']);
    Route::get('/properties', ['as' => 'properties', 'uses' => 'ProfileController@properties']);
});


Route::get('/callback', '\App\Http\Controllers\Frontend\SocialAuthController@callback');


Route::any('/resetpassword', [
  'as' => 'resetpassword',
  'uses' => '\App\Http\Controllers\Frontend\UserController@resetpassword',
]);





/* ---------------------BACK END ---------------------------------*/


Route::any('/admin/login', [
    'as' => 'admin.login', 
    'uses' => '\App\Http\Controllers\Backend\Auth\AuthController@login',
        
]);

Route::any('/admin/logout', [
    'as' => 'admin.logout', 
    'uses' => '\App\Http\Controllers\Backend\HomeController@logout',
    
]);



Route::group(['middleware' => ['auth', 'permissions'], 'prefix' => 'admin'], function()
{
    Route::any('/', [
        'as' => 'admin.index', 
        'uses' => '\App\Http\Controllers\Backend\HomeController@index',
        
    ]);

    Route::any('user/', [
        'as' => 'user.index', 
        'uses' => '\App\Http\Controllers\Backend\UserController@index',
        
    ]);
    Route::get('user/detail/{id}', [
        'as' => 'user.detail', 
        'uses' => '\App\Http\Controllers\Backend\UserController@detail',

    ]);
    Route::any('user/add', [
        'as' => 'user.add', 
        'uses' => '\App\Http\Controllers\Backend\UserController@add',

    ]);
    Route::any('user/update/{id}', [
        'as' => 'user.update', 
        'uses' => '\App\Http\Controllers\Backend\UserController@update',

    ]);
    Route::get('user/delete/{id}', [
        'as' => 'user.delete', 
        'uses' => '\App\Http\Controllers\Backend\UserController@delete',

    ]);

    Route::any('user/searchingbytypeahead', [
        'as' => 'user.ajax.searching', 
        'uses' => '\App\Http\Controllers\Backend\UserController@searchingByAjax',

    ]);

    Route::any('user/resetpassword/{id}', [
        'as' => 'user.resetpassword', 
        'uses' => '\App\Http\Controllers\Backend\UserController@resetPassword',

    ]);



    Route::any('role/', [
        'as' => 'role.index', 
        'uses' => '\App\Http\Controllers\Backend\RoleController@index',
        
    ]);
    Route::get('role/detail/{id}', [
        'as' => 'role.detail', 
        'uses' => '\App\Http\Controllers\Backend\RoleController@detail',

    ]);
    Route::any('role/add', [
        'as' => 'role.add', 
        'uses' => '\App\Http\Controllers\Backend\RoleController@add',

    ]);
    Route::any('role/update/{id}', [
        'as' => 'role.update', 
        'uses' => '\App\Http\Controllers\Backend\RoleController@update',

    ]);
    Route::get('role/delete/{id}', [
        'as' => 'role.delete', 
        'uses' => '\App\Http\Controllers\Backend\RoleController@delete',

    ]);

    

    Route::any('permission/', [
        'as' => 'permission.index', 
        'uses' => '\App\Http\Controllers\Backend\PermissionController@index',
        
    ]);
    Route::get('permission/detail/{id}', [
        'as' => 'permission.detail', 
        'uses' => '\App\Http\Controllers\Backend\PermissionController@detail',

    ]);
    Route::any('permission/add', [
        'as' => 'permission.add', 
        'uses' => '\App\Http\Controllers\Backend\PermissionController@add',

    ]);
    Route::any('permission/update/{id}', [
        'as' => 'permission.update', 
        'uses' => '\App\Http\Controllers\Backend\PermissionController@update',

    ]);
    Route::get('permission/delete/{id}', [
        'as' => 'permission.delete', 
        'uses' => '\App\Http\Controllers\Backend\PermissionController@delete',

    ]);
    Route::any('role/{roleId}/permission', [
        'as' => 'permission.set', 
        'uses' => '\App\Http\Controllers\Backend\PermissionController@setPermissionForRole',

    ]);


    //Post
    Route::any('properties/', [
        'as' => 'admin.post.index', 
        'uses' => '\App\Http\Controllers\Backend\PostController@index',

    ]);
    Route::any('properties/pending', [
        'as' => 'admin.post.pending', 

app/Http/Controllers/Frontend/BaseController.php
<?php namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;

class BaseController extends Controller {

}

app/Http/Controllers/Frontend/HomeController.php
<?php namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Frontend\BaseController;

use App\Http\Services\Frontend\TagService;

use ChannelLog as Log;

class HomeController extends BaseController {

	protected $tagService;

	public function __construct(TagService $tagService) 
	{
		$this->tagService = $tagService;

	}


	
	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('frontend.home.index');
	}

	public function about()
	{
		return view('frontend.about');
	}

	public function terms()
	{
		return view('frontend.terms');
	}

	public function privacy()
	{
		return view('frontend.privacy');
	}

	public function contact()
	{
		return view('frontend.contact');
	}

}

app/Http/Controllers/Frontend/SearchController.php
<?php namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Frontend\BaseController;

use ChannelLog as Log;


class SearchController extends BaseController {


	public function __construct() 
	{
		
	}

	/**
	 * Show the result
	 *
	 * @return Response
	 */
	public function result()
	{
		return view('frontend.post.list');
	}


	/**
	 * Show the search of tag page
	 * @return [type] [description]
	 */
	public function searchTag($slug)
	{
		return view('frontend.post.list');
	}

}

app/Http/Controllers/Frontend/SocialAuthController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Entities\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Socialite;
use Hash;

use ChannelLog as Log;

class SocialAuthController extends Controller
{
    public function index()
    {
        return view('social.index');
    }

    public function redirect()
    {
        return Socialite::driver('facebook')->redirect();
    }

    public function callback()
    {
        //dd(Socialite::driver('facebook')->user());
    }
}

app/Http/Controllers/Frontend/UserController.php
<?php namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Frontend\BaseController;

use App\Http\Requests\Frontend\RegisterRequest;
use App\Models\Entities\Base;
use App\Models\Entities\User;
use App\Models\Repositories\UserRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Mail;

use Hash;

use Auth;

use ChannelLog as Log;

class UserController extends BaseController {
	public $userRepository;

	public function __construct() {
		$this->userRepository = new UserRepository( new User() );
	}


	/**
	 * Register User
	 *
	 * @return Response
	 */
	public function getRegister() {
		return view( 'frontend.user.register' );
	}

	/**Store Register Information
	 *
	 * @param Request $request
	 */
	public function postRegister( Request $request ) {
		$registerRules = [
			'email'        => 'required|unique:user,email|max:255',
			'password'     => 'required|confirmed|max:60',
			'phone_number' => 'required|max:255',
			'address'	   => 'required|max:255',
			'fullname'     => 'required|max:255',
		];

		$validator = validator( $request->all(), $registerRules );

		if ( $validator->fails() ) {
			$this->throwValidationException(
				$request, $validator
			);
		}

		//Create new User
		$user = $this->userRepository->add( $request->all() );


		// Send Confirm email if  config On
		if ( config( 'asap.email_confirm' ) ) {
			$activationCode        = str_random( 12 );
			$user->activation_code = $activationCode;
			$user->status          = config('asap.user_status')['inactive'];
			$user->save();
			try {
				Mail::send( 'emails.user_confirm', [
					'user'           => $user,
					'activationCode' => $activationCode
				], function ( $m ) use ( $user ) {
					$m->to( $user->email, $user->name )->subject( 'Email confirm.' );
				} );
				flash()->overlay( 'We has been to you a Email to confirm. Please check it!', 'Email Confirm' );
			} catch (Exception $e) {
				return abort(500);
			}
				
		} else {
			$user->status = config('asap.user_status')['active'];
			$user->save();
			if (config( 'asap.email_confirm' )) {
				try {
					Mail::send( 'emails.thank_for_register', [
						'user' => $user,
					], function ( $m ) use ( $user ) {
						$m->to( $user->email, $user->name )->subject( 'Thank you.' );
					} );
				} catch (Exception $e) {
					return abort(500);
				}
			}
			flash()->overlay( 'Your account has been created! Please Login to use.', 'Register Successfull' );

		}

		return redirect()->to( '/' );

	}

	/**
	 * Email Confirm Proccessing
	 *
	 * @param $userId
	 * @param $activationCode
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function confirmEmail( $userId, $activationCode ) {
		$user = $this->userRepository->getById( $userId );
		if ( $user ) {
			if ( $user->activation_code == $activationCode ) {
				$user->status       = 1;
				$user->activated_at = Carbon::now();
				$user->save();
				flash()->overlay( 'Your account has been confirmed! Please Login to use.', 'Confirm email successfull' );

				return redirect()->to( '/' );
			} else {
				flash()->overlay( 'Confirm email failed, Please check email to confirm again !', 'Confirm email failed' );

				return redirect()->to( '/' );
			}
		} else {
			flash()->overlay( 'User not found', 'Confirm email failed, Please check email to confirm again!' );
		}

	}

}

app/Http/Controllers/Frontend/WishListController.php
<?php namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Frontend\BaseController;

use App\Http\Services\Frontend\WishlistService;
use App\Models\Repositories\WishlistRepository;
use App\Http\Services\Frontend\PostService;
use App\Models\Repositories\PostRepository;

use Illuminate\Http\Request;

use ChannelLog as Log;

class WishListController extends BaseController {

	protected $wishlistService;
	protected $wishlistRepository;
	protected $postService;
	protected $postRepository;

	public function __construct(WishlistService $wishlistService, WishlistRepository $wishlistRepository, PostService $postService, PostRepository $postRepository) 
	{
		$this->wishlistService = $wishlistService;
		$this->wishlistRepository = $wishlistRepository;
		$this->postService = $postService;
		$this->postRepository = $postRepository;
	}


	
	public function apiAdd(Request $request)
	{
		$input = $request->all();
		if (!empty($input)) {
			if (!$this->wishlistService->hasWishList($input['id'])) {
				$wl = $this->wishlistService->save($input['id']);
				return json_encode(array('code' => 1, 'mess' => 'Add wishlist success'));
			} else {
				return json_encode(array('code' => 1, 'mess' => 'Already added wishlist'));
			}
		}	

		return json_encode(array('code' => 0, 'mess' => 'Add to wishlist fail'));
	}



	public function apiRemove(Request $request)
	{
		$input = $request->all();
		if (!empty($input)) {
			if ($this->wishlistService->hasWishList($input['id'])) {
				$wl = $this->wishlistService->remove($input['id']);
				return json_encode(array('code' => 1, 'mess' => 'Remove wishlist success'));
			} else {
				return json_encode(array('code' => 1, 'mess' => 'Already removed wishlist'));
			}
		}

		return json_encode(array('code' => 0, 'mess' => 'Remove wishlist fail'));
	}


}

resources/views/frontend/partials/homepage_header.blade.php
<header>
    <div class="rs_index2_topheader">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="logo">
                        <a href="{{ route('frontend.index') }}"><img src="{{ asset('assets/common/images/logo-white-s.png') }}" class="img-responsive" alt="logo"></a>
                    </div>
                </div>
                @include('frontend.partials.user_nav')
            </div>
        </div>
    </div>
</header>

resources/views/frontend/partials/master_header.blade.php
<div class="rs_index2_topheader">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                <div class="logo">
                    <a href="{{ route('frontend.index') }}"><img src="{{ asset('assets/common/images/logo-white-s.png') }}" class="img-responsive" alt="logo"></a>
                </div>
            </div>
            @include('frontend.partials.user_nav')
        </div>
    </div>
</div>

resources/views/frontend/partials/notification_modal.blade.php
<div class="modal fade" id="notificationModal" role="dialog">
    <div class="modal-dialog" style="width: 40% !important;">
        <div class="modal-content" style="border-radius: 0 !important;">
            <div class="modal-body">
                <h2 class="modal-title text-center" id="notificationTitle">Notification</h2>
                <div class="clearfix">

                </div>
                <p class="text-center">
                    <button name="btnClose" type="button" class="btn btn-default btnClose" data-dismiss="modal">Close
                    </button>
                </p>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    #notificationModal {
        top: 20%;
    }

    h2#notificationTitle {
        margin-top: 15px;
        margin-bottom: 30px;
    }

    #notificationModal button.btnClose {
        font-weight: bold;
        color: #fff;
        text-align: center;
        white-space: nowrap;
        border: none;
        font-size: 18px;
        border-radius: 60px;
        padding: 0.5em 4em;
        text-decoration: none;
        display: inline-block;
        background: red;
    }

    #notificationModal button.btnClose:hover {
        background: #ff4040;
    }
</style>

resources/views/frontend/partials/user_nav.blade.php
@if(auth()->check())
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 user-nav">
        <div class="rs_user_pic">
            <div>
                <h6>{{auth()->user()->fullname}}</h6>
            </div>
            <img src="{{ asset(auth()->user()->getProfilePicture()) }}" alt="">
            <i class="glyphicon glyphicon-option-vertical" aria-hidden="true"></i>
        </div>
        <div class="rs_user_profile">
            <ul>
                <li><a href="{{ route('frontend.profile.me') }}"><i class="fa fa-user"></i>Profile</a></li>
                <li><a href="{{ route('logout') }}"><i class="fa fa-download"></i> Sign Out</a></li>
            </ul>
        </div>
        <!-- <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><i class="fa fa-heart"></i> (28)</a></li>
            <li><a href="cart.html"><i class="fa fa-shopping-cart"></i> (2)</a></li>
        </ul> -->
    </div>
@else
    <div class="col-lg-4 col-md-8 col-sm-12 col-xs-12 pull-right">
        <div class="rs_index2_topheader_links">
            <ul>
                <li><a href="#" data-toggle="modal" data-target="#login_popup">Login</a></li>
                <li><a href="/register">Signup</a></li>
            </ul>
            <!-- Modal -->
            <div class="modal fade rs_mypopup" id="login_popup" tabindex="-1" role="dialog">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                   
                  </div>
                  <div class="modal-body">
                    <div class="rs_popup_list">
                        <ul>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_1.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>30 days Money Back Guarantee</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_2.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>New Items Are Included in same subscribtions</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_3.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>24/7 Dedicated Customer Support</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_6.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>100% Secured Payment Gateway</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="rs_popup_form">
                        <div class="rs_popup_form_header">
                            <img src="{{ asset('assets/frontend/images/logo.png') }}" class="img-responsive" alt="">
                            <h4 class="text-uppercase">Login in to Property Asap</h4>
                        </div>
                        <form class="form-horizontal" role="form" method="POST" action="{{ url('/login') }}">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <input type="text" name="email" class="form-control" placeholder="Enter your mail address">
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" class="form-control" placeholder="Password">
                                <a href="{{url('/password/reset')}}">Forget your password?</a>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="rs_button rs_button_orange">Login</button>
                                <h4>or</h4>
                                <a href="{{ route('frontend.auth.facebook.callback') }}" class="rs_button rs_button_darkblue"><i class="fa fa-facebook"></i> Log in Via Facebook</a>
                                <h4>or</h4>
                                <a href="{{ route('frontend.auth.google.callback') }}" class="rs_button rs_button_red"><i class="fa fa-google"></i> Log in Via Google</a>
                            </div>
                        </form>
                        <p>Don’t have account yet? <a href="{{url('register')}}">signup <i class="fa fa-angle-double-right"></i></a></p>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
            
            <div class="modal fade rs_mypopup rs_signup" id="signup_popup" tabindex="-1" role="dialog">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                   
                  </div>
                  <div class="modal-body">
                    <div class="rs_popup_list">
                        <ul>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_1.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>30 days Money Back Guarantee</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_2.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>New Items Are Included in same subscribtions</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_3.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>24/7 Dedicated Customer Support</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                            <li>
                                <div class="rs_popup_list_img"><img src="{{ asset('assets/frontend/images/af_6.jpg') }}" alt="" class="img-responsive"></div>
                                <div class="rs_popup_list_data">
                                    <h5>100% Secured Payment Gateway</h5>
                                    <p>We are a fairly small, flexible design studio that designs for print and web. We work flexibly with clients</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="rs_popup_form">
                        <div class="rs_popup_form_header">
                            <img src="{{ asset('assets/frontend/images/logo.png') }}" class="img-responsive" alt="">
                            <h4 class="text-uppercase">Create Your Account</h4>
                        </div>
                        <form>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="User Name">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Enter your mail address">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" placeholder="Password">
                            </div>
                            <div class="rs_form_checkbox">
                                <div class="rs_checkbox">
                                    <input type="checkbox" value="1" id="check4" name="checkbox">
                                    <label for="check4"></label>
                                </div>
                                <p>I'd like to hear about promos, new templates, and much more! </p>
                            </div>
                            <div class="rs_form_checkbox">
                                <div class="rs_checkbox">
                                    <input type="checkbox" value="1" id="check5" name="checkbox">
                                    <label for="check5"></label>
                                </div>
                                <p>By clicking "Sign up" you agree to our Terms of Service and Privacy Policy</p>
                            </div>
                            <div class="form-group">
                                <a href="#" class="rs_button rs_button_orange">Login</a>
                                <h4>or</h4>
                                <a href="#" class="rs_button rs_button_darkblue"><i class="fa fa-facebook"></i> Log in Via Facebook</a>
                            </div>
                        </form>
                        <p>Already have an account? <a href="#">login <i class="fa fa-angle-double-right"></i></a></p>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
        </div>
    </div>
@endif